version: "3.8"

services:
  web:
    container_name: web
    build: 
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    networks: 
      - app_network  
  backend:         
    container_name: backend
    build: 
        context: .
        dockerfile: ./apps/backend/Dockerfile
    restart: always    
    networks: 
      - app_network
    
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true    


              
