version: "3.8"

services:
  web:
    container_name: web
      build: 
        context: .
        dockerfile: ./app/web/Dockerfile
      restart: always
      port: 
        - 3000:3000
      networks: 
        - app_network  
  backend:         
    container_name: backend
    build: 
        context: .
        dockerfile: ./app/backend/Dockerfile
    restart: always    
    port: 
      - 3001:3001
    networks: 
      - app_network
    
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    external: true    


              
