FROM node:20-alpine  AS base


FROM base AS builder
RUN apk update
RUN apk add --no-cache libc6-compat
# Set working directory
WORKDIR /app

RUN npm install -g turbo
COPY . .
RUN turbo prune backend --docker


# Add lockfile and package.json's of isolated subworkspace
FROM base AS installer
RUN apk update
RUN apk add --no-cache libc6-compat
WORKDIR /app

# First install dependencies (as they change less often)
COPY --from=builder /app/out/json/ .
RUN npm install

RUN npm run build:backend

FROM base AS runner
WORKDIR /app

EXPOSE 3001

CMD ["node","apps/backend/dist/index.js"]